### PR TITLE
build(dependencies): move optional dependencies to peerdependencies

### PR DESCRIPTION
**Pull request by antoniopacheco**
Moved libraries from optionalDependencies to peerDependencies to be truely zero-dependency
 #281 
if this is not, then there is multiple instances of react in the same project.
and this will cause conflicts while using react hooks 
https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

a `npm ls react` 
will show you 2 different instances of react

### CODE REVIEW

**Comment by adamtew** [comment]
@antoniopacheco Should this just change the `optionalDependencies` to `peerDependencies`? Or is it necessary to also move `jquery` and `react` into `dependencies`?

**Comment by antoniopacheco** [comment]
@adamtew it  changes the `optionalDependencies` to `peerDependencies` .
but it also adds jquery and react to `devDependencies` so, whenever anyone needs to work in this repo, won't need them to install manually or globally

**Comment by adamtew** [comment]
Lol, I should have scrolled up to see they were in `devDependencies` not `dependencies` 🤦‍♂

**Comment by Zertz** [comment]
Yarn installs `optionalDependencies` so Linkify is never "a zero-dependency JavaScript plugin" for Yarn users 😥 

It would be super convenient for us to have this released 😊

**Comment by chinaowl** [comment]
When might this get released?

**Comment by benchun** [comment]
@antoniopacheco anything else needed before this can be merged? Looks like @Soreine approved.

**Comment by nfrasser** [comment]
Hi all, apologies for the delay on this. This is now published as `linkifyjs@2.1.9`

**Comment by Zertz** [comment]
No worries, thanks @nfrasser 😊

**Pull request merged**
