### PR TITLE
Use class instead of React.createClass

### PR DESCRIPTION
**Pull request by djagya**
Fixes issue #196

### CODE REVIEW

**Comment by fpayer** [comment]
@nfrasser Can we get this merged in? createClass is being deprecated.

**Comment by niklaskorz** [comment]
@grahammccarthy hasn't been active on Github since January and is the only person associated with the SoapBox github organization. I suppose there won't be any updates coming from SoapBox in the foreseeable future, so a community-maintained fork might be the only viable option.

**Comment by grahammccarthy** [comment]
Hey guys! This is still an active project. I'm active just not on any public projects.
Let me reach out to @nfrasser to see what he is thinking in terms of maintaining this project and getting this PR pushed in. :)

**Comment by artdent** [comment]
Hi, @grahammccarthy and @nfrasser, any news on getting this merged? React.createClass will be removed in React 16, which is now in release candidate phase.

**Pull request merged**
